# fly.toml app configuration file generated for ai-cv-builder-be on 2025-06-07T04:08:01+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-cv-builder-be'
primary_region = 'bom'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
